routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@main')->name('page.main');
Route::get('/about', 'PageController@about')->name('page.about');
Route::get('/contacts', 'PageController@contacts')->name('page.contacts');
Route::get('/policy', 'PageController@policy')->name('page.policy');
Route::get('/cookie', 'PageController@cookie')->name('page.cookie');
Route::resource('service', 'ServiceController')->only(['show']);
Route::get('/services', 'ServiceController@index')->name('service.index');
Route::resource('project', 'ProjectController')->only(['show']);
Route::get('/projects', 'ProjectController@index')->name('project.index');
Route::resource('product', 'ProductController')->only(['show']);
Route::get('/products/{categoria?}/{attributes?}', 'ProductController@index')->name('product.index');
Route::resource('problem', 'ProblemController')->only('store');
Route::post('/enter', 'UserController@login')->name('user.login');
Route::get('/login', 'UserController@loginPage')->name('user.login_page');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/logout', 'UserController@logout')->name('user.logout');
      
    Route::resource('attribute', 'AttributeController')->except(['show']);
    Route::resource('attribute_type', 'AttributeTypeController')->except(['show']);
    Route::resource('problem', 'ProblemController')->only(['destroy', 'index', 'show']);
    Route::resource('product', 'ProductController')->except(['index', 'show']);
    Route::get('/products', 'ProductController@listing')->name('product.listing');
    Route::resource('product_category', 'ProductCategoryController')->except(['show']);
    Route::resource('common_seo', 'CommonSeoController')->only(['edit', 'update']);
	Route::resource('worker', 'WorkerController')->except(['show']);
    Route::resource('license', 'LicenseController')->except(['show']);
    Route::resource('banner', 'BannerController')->except(['show']);
    Route::resource('setting', 'SettingController')->only(['update', 'edit']);
    Route::resource('user', 'UserController')->except('show');
    Route::resource('project', 'ProjectController')->except(['index', 'show', 'update']);
    Route::post('/project_store/{id}', 'ProjectController@update');
    Route::get('/projects', 'ProjectController@listing')->name('project.listing');
    Route::resource('service', 'ServiceController')->except(['index', 'show']);
    Route::get('/services', 'ServiceController@listing')->name('service.listing');
    Route::get('/common_image/{id}', 'CommonImageController@destroy')->name('common_image.destroy');
});

resources/views/admin/licenses/create.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Добавить лицензию
            </h2>
        </div>
        <div class="body">
            {{ Form::open(['method' => 'POST', 'files' => true, 'url' => route('license.store')]) }}
            @if (count($errors) > 0)
                <div class="row clearfix">
                    <div class="col-sm-6 alert alert-danger alert-dismissable col-sm-offset-3">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach ($errors->all() as $message)
                            <div class="">
                                {{$message}}
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Подпись</label>
                            <input name="title" type="text" class="form-control"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <label class="form-label col-sm-12">Изображение</label>
                        <img class="img-responsive img-thumbnail">
                        <div class="btn-group bootstrap-select form-control show-tick">
                            <input class="one-img-upload" type="file" name="img">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-3"></div>
                <input type="submit" class="btn btn-primary col-sm-6 text-center" value="Добавить">
            </div>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/admin/licenses/edit.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Редактировать лицензию
            </h2>
        </div>
        <div class="body">
            {{ Form::open(['method' => 'PATCH', 'files' => true, 'url' => route('license.update', ['id' => $license->id])]) }}
            @if (count($errors) > 0)
                <div class="row clearfix">
                    <div class="col-sm-6 alert alert-danger alert-dismissable col-sm-offset-3">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach ($errors->all() as $message)
                            <div class="">
                                {{$message}}
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Подпись</label>
                            <input name="title" type="text" class="form-control" value="{{ $license->title }}"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <label class="form-label col-sm-12">Изображение</label>
                        <img src="{{ Storage::url($license->img) }}" class="img-responsive img-thumbnail">
                        <div class="btn-group bootstrap-select form-control show-tick">
                            <input class="one-img-upload" type="file" name="img">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-3"></div>
                <input type="submit" class="btn btn-primary col-sm-6 text-center" value="Редактировать  ">
            </div>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/admin/licenses/list.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Список лицензий
            </h2>
            <ul class="header-dropdown m-r--5">
                <a href="{{route('license.create')}}" class="btn btn-primary waves-effect">Добавить лицензию</a>
            </ul>
        </div>
        <div class="body table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Изображение</th>
                    <th>Подпись</th>
                    <th class="text-center">Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($licenses as $item)
                    <tr>
                        <th scope="row">{{ $item->id }}</th>
                        <td><img class="img-thumbnail col-sm-2" src="{{ Storage::url($item->img('default', 'img')) }}"></td>
                        <td>{{ $item->title }}</td>
                        <td>
                            {{ Form::open(['method' => 'DELETE', 'url' => route('license.destroy', ['id' => $item->id])]) }}
                                <button class="col-sm-offset-3 btn btn-danger waves-effect col-sm-5" type="submit">Удалить</button>
                            {{ Form::close() }}
                            <a href="{{route('license.edit', ['id' => $item->id]) }}" class="col-sm-offset-3 btn btn-warning waves-effect col-sm-5">Редактировать</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $licenses->render() }}
        </div>
    </div>
@stop