routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@main')->name('page.main');
Route::get('/about', 'PageController@about')->name('page.about');
Route::get('/contacts', 'PageController@contacts')->name('page.contacts');
Route::get('/policy', 'PageController@policy')->name('page.policy');
Route::get('/cookie', 'PageController@cookie')->name('page.cookie');
Route::resource('service', 'ServiceController')->only(['show']);
Route::get('/services', 'ServiceController@index')->name('service.index');
Route::resource('project', 'ProjectController')->only(['show']);
Route::get('/projects', 'ProjectController@index')->name('project.index');
Route::resource('product', 'ProductController')->only(['show']);
Route::get('/products/{categoria?}/{attributes?}', 'ProductController@index')->name('product.index');
Route::resource('problem', 'ProblemController')->only('store');
Route::post('/enter', 'UserController@login')->name('user.login');
Route::get('/login', 'UserController@loginPage')->name('user.login_page');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/logout', 'UserController@logout')->name('user.logout');
      
    Route::resource('attribute', 'AttributeController')->except(['show']);
    Route::resource('attribute_type', 'AttributeTypeController')->except(['show']);
    Route::resource('problem', 'ProblemController')->only(['destroy', 'index', 'show']);
    Route::resource('product', 'ProductController')->except(['index', 'show']);
    Route::get('/products', 'ProductController@listing')->name('product.listing');
    Route::resource('product_category', 'ProductCategoryController')->except(['show']);
    Route::resource('common_seo', 'CommonSeoController')->only(['edit', 'update']);
	Route::resource('worker', 'WorkerController')->except(['show']);
    Route::resource('license', 'LicenseController')->except(['show']);
    Route::resource('banner', 'BannerController')->except(['show']);
    Route::resource('setting', 'SettingController')->only(['update', 'edit']);
    Route::resource('user', 'UserController')->except('show');
    Route::resource('project', 'ProjectController')->except(['index', 'show', 'update']);
    Route::post('/project_store/{id}', 'ProjectController@update');
    Route::get('/projects', 'ProjectController@listing')->name('project.listing');
    Route::resource('service', 'ServiceController')->except(['index', 'show']);
    Route::get('/services', 'ServiceController@listing')->name('service.listing');
    Route::get('/common_image/{id}', 'CommonImageController@destroy')->name('common_image.destroy');
});

resources/views/admin/elements/header.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ route('user.edit', ['id' => Auth::user()->id]) }}">ELYGARDEN - админ панель</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{{ route('page.main') }}" target="_blank" class="js-search" data-close="true">
                        <div class="demo-google-material-icon">
                            <i class="material-icons" style="float:left;margin-top:8px;">redo</i>
                            <span class="icon-name" style="float:left;margin-top:10px;">На сайт</span>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/elements/notification.blade.php
@if (Session::has('message'))
    <div class="animated fadeInDown common-alert">
        <button class="close common-close">×</button>
        <span data-notify="icon"></span>
        <span data-notify="title"></span>
        <h4 data-notify="message">{{ Session::get('message') }}</h4>
        <a href="#" target="_blank" data-notify="url"></a>
    </div>
@endif

resources/views/admin/elements/page_loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

resources/views/admin/elements/sidebar.blade.php
<section>
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="{{route('user.logout')}}"><i class="material-icons">input</i>выход</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="menu">
            <ul class="list">
                <li class="header">Навигация</li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block toggled">
                        <i class="material-icons">event</i>
                        <span>Атрибуты</span>
                    </a>
                    <ul class="ml-menu" style="display: block;">
                        <li class="{{ route('attribute.index') === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('attribute.index') }}">
                                <span>Атрибуты</span>
                            </a>
                        </li>
                        <li class="{{ route('attribute_type.index') === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('attribute_type.index') }}">
                                <span>Типы атрибутов</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block toggled">
                        <i class="material-icons">card_travel</i>
                        <span>Продукты</span>
                    </a>
                    <ul class="ml-menu" style="display: block;">
                        <li class="{{ route('product.listing') === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('product.listing') }}">
                                <span>Продукты</span>
                            </a>
                        </li>
                        <li class="{{ route('product_category.index') === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('product_category.index') }}">
                                <span>Категории продуктов</span>
                            </a>
                        </li>
                    </ul>
                </li> 
                <li class="{{ route('project.listing') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('project.listing') }}">
                        <i class="material-icons">create</i>
                        <span>Проекты</span>
                    </a>
                </li> 
                <li class="{{ route('service.listing') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('service.listing') }}">
                        <i class="material-icons">create</i>
                        <span>Услуги</span>
                    </a>
                </li>
                <li class="{{ route('banner.index') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('banner.index') }}">
                        <i class="material-icons">create</i>
                        <span>Баннеры</span>
                    </a>
                </li>
                <li class="{{ route('license.index') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('license.index') }}">
                        <i class="material-icons">create</i>
                        <span>Лицензии</span>
                    </a>
                </li>
                <li class="{{ route('worker.index') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('worker.index') }}">
                        <i class="material-icons">create</i>
                        <span>Работники</span>
                    </a>
                </li>              
                <li class="{{ route('problem.index') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('problem.index') }}">
                        <i class="material-icons">live_help</i>
                        <span>Вопросы</span>
                    </a>
                </li>
                <li class="{{ route('user.index') === URL::current() ? 'active' : '' }}">
                    <a href="{{ route('user.index') }}">
                        <i class="material-icons">people_outline</i>
                        <span>Пользователи</span>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0);" class="menu-toggle waves-effect waves-block toggled">
                        <i class="material-icons">settings</i>
                        <span>Общие настройки</span>
                    </a>
                    <ul class="ml-menu" style="display: block;">
                        <li class="{{ route('common_seo.edit', ['id' => 1]) === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('common_seo.edit', ['id' => 1]) }}">
                                <span>Общее SEO</span>
                            </a>
                        </li>
                        <li class="{{ route('setting.edit', ['id' => 1]) === URL::current() ? 'active' : '' }}">
                            <a href="{{ route('setting.edit', ['id' => 1]) }}">
                                <span>Контактная информация</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </aside>
</section>