routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@main')->name('page.main');
Route::get('/about', 'PageController@about')->name('page.about');
Route::get('/contacts', 'PageController@contacts')->name('page.contacts');
Route::get('/policy', 'PageController@policy')->name('page.policy');
Route::get('/cookie', 'PageController@cookie')->name('page.cookie');
Route::resource('service', 'ServiceController')->only(['show']);
Route::get('/services', 'ServiceController@index')->name('service.index');
Route::resource('project', 'ProjectController')->only(['show']);
Route::get('/projects', 'ProjectController@index')->name('project.index');
Route::resource('product', 'ProductController')->only(['show']);
Route::get('/products/{categoria?}/{attributes?}', 'ProductController@index')->name('product.index');
Route::resource('problem', 'ProblemController')->only('store');
Route::post('/enter', 'UserController@login')->name('user.login');
Route::get('/login', 'UserController@loginPage')->name('user.login_page');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::get('/logout', 'UserController@logout')->name('user.logout');
      
    Route::resource('attribute', 'AttributeController')->except(['show']);
    Route::resource('attribute_type', 'AttributeTypeController')->except(['show']);
    Route::resource('problem', 'ProblemController')->only(['destroy', 'index', 'show']);
    Route::resource('product', 'ProductController')->except(['index', 'show']);
    Route::get('/products', 'ProductController@listing')->name('product.listing');
    Route::resource('product_category', 'ProductCategoryController')->except(['show']);
    Route::resource('common_seo', 'CommonSeoController')->only(['edit', 'update']);
	Route::resource('worker', 'WorkerController')->except(['show']);
    Route::resource('license', 'LicenseController')->except(['show']);
    Route::resource('banner', 'BannerController')->except(['show']);
    Route::resource('setting', 'SettingController')->only(['update', 'edit']);
    Route::resource('user', 'UserController')->except('show');
    Route::resource('project', 'ProjectController')->except(['index', 'show', 'update']);
    Route::post('/project_store/{id}', 'ProjectController@update');
    Route::get('/projects', 'ProjectController@listing')->name('project.listing');
    Route::resource('service', 'ServiceController')->except(['index', 'show']);
    Route::get('/services', 'ServiceController@listing')->name('service.listing');
    Route::get('/common_image/{id}', 'CommonImageController@destroy')->name('common_image.destroy');
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    public $timestamps = false;

    /**
     * @var string
     */
    protected $table = 'attributes';

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'type_id',
        'type_cat_id',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function type()
    {
        return $this->belongsTo('App\Models\AttributeType', 'type_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function category()
    {
        return $this->belongsTo('App\Models\ProductCategory', 'type_cat_id', 'id');
    }

    /**
     * Возвращает условия для Eloquent построителя запросов
     * Условие - коревой уровень категорий.
     *
     * @param $query
     * @param $categoryId
     * @return mixed
     */
    public function scopeCategoryAttributes($query, $categoryId)
    {
        return $query->where('type_cat_id', '=', $categoryId);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->belongsToMany(
            'App\Models\Product', 
            'product_attribute', 
            'product_id', 
            'attribute_id'
        );
    }
}

app/Models/AttributeType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AttributeType extends Model
{
    public $timestamps = false;
    
    /**
     * @var string
     */
    protected $table = 'attribute_types';

    /**
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attributes()
    {
        return $this->hasMany('App\Models\Attribute', 'type_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('App\Models\ProductCategory', 'attribute_type_category', 'attribute_type_id', 'category_id');
    }
}

app/Http/Controllers/AttributeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Attribute;
use App\Models\AttributeType;
use App\Models\ProductCategory;
use App\Http\Requests\AttributeRequest;

class AttributeController extends Controller
{
    /**
     * @var
     */
    private $attribute;

    /**
     * @var
     */
    private $productCategory;

    /**
     * @var
     */
    private $attributeType;

    /**
     * @param attribute $attribute
     */
    public function __construct (
        Attribute $attribute,
        AttributeType $attributeType,
        ProductCategory $productCategory
    )
    {
        $this->attribute = $attribute;
        $this->attributeType = $attributeType;
        $this->productCategory = $productCategory;
    }   
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $attributes = $this->attribute::paginate(15);

        return view('admin.attributes.list', ['attributes' => $attributes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $attributeTypes = $this->attributeType::all();
        $productCategories = $this->productCategory::all();

        return view('admin.attributes.create', 
            [
                'attributeTypes' => $attributeTypes,
                'productCategories' => $productCategories,
            ]
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AttributeRequest $request)
    {
        $this->attribute::create($request->except('_token'));

        return redirect()->route('attribute.index')->with('message', 'Новый атрибут успешно добавлен!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\attribute  $attribute
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $attribute = $this->attribute::findOrFail($id);
        $attributeTypes = $this->attributeType::all();
        $productCategories = $this->productCategory::all();

        return view('admin.attributes.edit', 
            [
                'attribute' => $attribute, 
                'attributeTypes' => $attributeTypes,
                'productCategories' => $productCategories,
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\attribute  $attribute
     * @return \Illuminate\Http\Response
     */
    public function update(AttributeRequest $request, $id)
    {
        $this->attribute::findOrFail($id)->update($request->except('_token'));

        return redirect()->route('attribute.index')->with('message', 'Атрибут успешно изменен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\attribute  $attribute
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->attribute::findOrFail($id)->delete();

        return redirect()->back()->with('message', 'Атрибут успешно удален!');
    }
}

resources/views/admin/attributes/create.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Добавить атрибут
            </h2>
        </div>
        <div class="body">
            {{ Form::open(['method' => 'POST', 'url' => route('attribute.store')]) }}
            @if (count($errors) > 0)
                <div class="row clearfix">
                    <div class="col-sm-6 alert alert-danger alert-dismissable col-sm-offset-3">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach ($errors->all() as $message)
                            <div class="">
                                {{$message}}
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Название</label>
                            <input name="name" type="text" class="form-control" value="{{ old('name') }}"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Тип атрибута</label>
                            <select name="type_id" class="form-control show-tick">
                                <option value="">— Please select —</option>
                                @foreach($attributeTypes as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
             <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Категория продукта, к которой относится атрибут</label>
                            <select name="type_cat_id" class="form-control show-tick">
                                <option value="">— Please select —</option>
                                @foreach($productCategories as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-3"></div>
                <input type="submit" class="btn btn-primary col-sm-6 text-center" value="Добавить">
            </div>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/admin/attributes/edit.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Редактировать атрибут
            </h2>
        </div>
        <div class="body">
            {{ Form::open(['method' => 'PATCH', 'url' => route('attribute.update', ['id' => $attribute->id])]) }}
            @if (count($errors) > 0)
                <div class="row clearfix">
                    <div class="col-sm-6 alert alert-danger alert-dismissable col-sm-offset-3">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        @foreach ($errors->all() as $message)
                            <div class="">
                                {{$message}}
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Название</label>
                            <input name="name" type="text" class="form-control" value="{{ $attribute->name }}"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <select class="form-control show-tick" name="type_id">
                        <option selected value="{{ $attribute->type->id }}">{{ $attribute->type->name }}</option>
                        @foreach($attributeTypes as $item) 
                            <option value="{{ $item->id }}">{{ $item->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-6 col-sm-offset-3">
                    <div class="form-group">
                        <div class="form-line">
                            <label>Категория продукта, к которой относится атрибут</label>
                            <select name="type_cat_id" class="form-control show-tick">
                                <option selected value="{{ $attribute->category->id }}">{{ $attribute->category->name }}</option>
                                @foreach($productCategories as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-sm-3"></div>
                <input type="submit" class="btn btn-primary col-sm-6 text-center" value="Редактировать">
            </div>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/admin/attributes/list.blade.php
@extends('admin.layout')
@section('content')
    <div class="card">
        <div class="header">
            <h2>
                Список атрибутов
            </h2>
            <ul class="header-dropdown m-r--5">
                <a href="{{route('attribute.create')}}" class="btn btn-primary waves-effect">Добавить атрибут</a>
            </ul>
        </div>
        <div class="body table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th class="text-center">Действия</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($attributes as $item)
                    <tr>
                        <th scope="row">{{ $item->id }}</th>
                        <td>{{ $item->name }}</td>
                        <td>
                            {{ Form::open(['method' => 'DELETE', 'url' => route('attribute.destroy', ['id' => $item->id])]) }}
                                <button class="col-sm-offset-3 btn btn-danger waves-effect col-sm-5" type="submit">Удалить</button>
                            {{ Form::close() }}
                            <a href="{{route('attribute.edit', ['id' => $item->id]) }}" class="col-sm-offset-3 btn btn-warning waves-effect col-sm-5">Редактировать</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{ $attributes->render() }}
        </div>
    </div>
@stop